import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#F9F8F3",
        "surface-bright": "#F9F8F3",
        "surface-dim": "#E5E3D8",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F3EFE6",
        "surface-container": "#ECE7DC",
        "surface-container-high": "#E2DDD2",
        "surface-container-highest": "#D7D2C5",
        "on-surface": "#1B281D",
        "on-surface-variant": "#49554B",
        outline: "#727972",
        "outline-variant": "#C2C8C0",
        
        primary: "#32533C",
        "primary-container": "#4A6B53",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#C5EACC",
        "primary-fixed": "#C7ECCE",
        "primary-fixed-dim": "#ABCFB2",
        "on-primary-fixed": "#01210F",
        "on-primary-fixed-variant": "#2E4E37",
        
        secondary: "#396663",
        "secondary-container": "#BCECE8",
        "on-secondary": "#FFFFFF",
        "on-secondary-container": "#3F6C69",
        "secondary-fixed": "#BCECE8",
        "secondary-fixed-dim": "#A1CFCC",
        "on-secondary-fixed": "#00201F",
        "on-secondary-fixed-variant": "#204E4B",
        
        tertiary: "#614633",
        "tertiary-container": "#7B5D49",
        "on-tertiary": "#FFFFFF",
        "on-tertiary-container": "#FFD9C1",
        "tertiary-fixed": "#FFDCC5",
        "tertiary-fixed-dim": "#E5BFA7",
        "on-tertiary-fixed": "#2B1707",
        "on-tertiary-fixed-variant": "#5B412F",
        
        error: "#BA1A1A",
        "on-error": "#FFFFFF",
        "error-container": "#FFDAD6",
        "on-error-container": "#93000A",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "space-lg": "2rem",
        "space-xl": "3.5rem",
        "margin-mobile": "1.25rem",
        gutter: "1.5rem",
        "space-md": "1.25rem",
        "space-sm": "0.75rem",
        "space-xs": "0.375rem",
        margin: "2.5rem",
      },
      fontFamily: {
        serif: ["var(--font-playfair)", "Playfair Display", "serif"],
        sans: ["var(--font-be-vietnam)", "Be Vietnam Pro", "sans-serif"],
        display: ["var(--font-playfair)", "Playfair Display", "serif"],
        headline: ["var(--font-playfair)", "Playfair Display", "serif"],
        body: ["var(--font-be-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "display-lg": ["var(--font-playfair)", "Playfair Display", "serif"],
        "headline-lg": ["var(--font-playfair)", "Playfair Display", "serif"],
        "headline-md": ["var(--font-playfair)", "Playfair Display", "serif"],
        "headline-sm": ["var(--font-playfair)", "Playfair Display", "serif"],
        "body-lg": ["var(--font-be-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "body-md": ["var(--font-be-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "body-sm": ["var(--font-be-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "label-lg": ["var(--font-be-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "label-md": ["var(--font-be-vietnam)", "Be Vietnam Pro", "sans-serif"],
        "label-sm": ["var(--font-be-vietnam)", "Be Vietnam Pro", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
